name: B站监控自动刷新
on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 刷新所有用户
        run: |
          curl -s "https://xiari.pythonanywhere.com/api/check?user=王欣虎扑"
          curl -s "https://xiari.pythonanywhere.com/api/check?user=王悦虎扑"
          curl -s "https://xiari.pythonanywhere.com/api/check?user=王欣旭宝"
          curl -s "https://xiari.pythonanywhere.com/api/check?user=王悦旭宝"
